namespace ProgramInformationV2.Data.PageList {

    public static class PageGroup {

        private static readonly Dictionary<SidebarEnum, List<PageLink>> _breadcrumbs = new() {
            { SidebarEnum.Configuration, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources") } },
            { SidebarEnum.ConfigurationNoSource, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources") } },
            { SidebarEnum.FieldsUsed, new() { new ("Home", "/"),
                                 new ("Configuration", "/configuration/sources"),
                                 new ("Fields Used", "/configuration/fieldsused/programs") } },
            { SidebarEnum.ProgramCredential, new() { new ("Home", "/"),
                                 new ("Programs and Credentials", "/programcred") } },
            { SidebarEnum.Program, new() { new ("Home", "/"),
                                 new ("Programs and Credentials", "/programcred"),
                                 new ("Programs", "/programs") } },
            { SidebarEnum.ProgramWithCredential, new() { new ("Home", "/"),
                                 new ("Programs and Credentials", "/programcred"),
                                 new ("Programs", "/programs") } },
            { SidebarEnum.Credential, new() { new ("Home", "/"),
                        new ("Programs and Credentials", "/programcred"),
                        new ("Credentials", "/credentials") } },
            { SidebarEnum.Courses, new() { new ("Home", "/"),
                        new ("Courses", "/courses") } },
            { SidebarEnum.Course, new() { new ("Home", "/"),
                        new ("Courses", "/courses") } },
            { SidebarEnum.CourseWithSection, new() { new ("Home", "/"),
                        new ("Courses", "/courses") } },
            { SidebarEnum.RequirementSets, new() { new ("Home", "/"),
                        new ("Requirement Sets", "/requirementsets") } },
            { SidebarEnum.RequirementSet, new() { new ("Home", "/"),
                        new ("Requirement Sets", "/requirementsets") } },
            { SidebarEnum.Section, new() { new ("Home", "/"),
                        new ("Courses", "/courses"),
                        new ("Course", "/course/general") } }
        };

        private static readonly Dictionary<SidebarEnum, List<PageLink>> _sidebars = new() {
            { SidebarEnum.None, [] },
            { SidebarEnum.EditInformation, new() { new ("Programs & Credentials", "/programcred"),
                                     new ("Courses & Sections", "/coursesection"),
                                     new ("Requirement Sets", "/requirementset") } },
            { SidebarEnum.ProgramCredential, new() { new ("Programs And Credentials", "/programcred"),
                                     new ("Programs", "/programs"),
                                     new ("Credentials", "/credentials") } },
            { SidebarEnum.Program, new() { new ("General Information", "/program/general"),
                                 new ("Link and Image", "/program/link"),
                                 new ("Overview", "/program/overview"),
                                 new ("Filters", "/program/filters"),
                                 new ("Related Links", "/program/relatedlinks"),
                                 new ("Technical Information", "/program/technical") } },
            { SidebarEnum.ProgramWithCredential, new() { new ("General Information", "/program/general"),
                                 new ("Link and Image", "/program/link"),
                                 new ("Overview", "/program/overview"),
                                 new ("Credential List", "/program/credentiallist"),
                                 new ("Related Links", "/program/relatedlinks"),
                                 new ("Technical Information", "/program/technical") } },
            { SidebarEnum.Credential, new() { new ("General Information", "/credential/general"),
                                 new ("Link and Image", "/credential/link"),
                                 new ("Overview", "/credential/overview"),
                                 new ("Filters", "/credential/filters"),
                                 new ("Related Links", "/credential/relatedlinks"),
                                 new ("Course List", "/credential/courselist"),
                                 new ("Transcript Information", "/credential/transcriptable"),
                                 new ("Technical Information", "/credential/technical") } },
            { SidebarEnum.Courses, new() { new ("Courses", "/courses"),
                                   new ("Import Courses", "/courses/import") } },
            { SidebarEnum.Course, new() { new ("General Information", "/course/general"),
                                 new ("Link and Image", "/course/link"),
                                 new ("Overview", "/course/overview"),
                                 new ("Filters", "/course/filters"),
                                 new ("Related Links", "/course/relatedlinks"),
                                 new ("Location & Time", "/course/locationtime"),
                                 new ("Faculty", "/course/faculty"),
                                 new ("Technical Information", "/course/technical") } },
            { SidebarEnum.CourseWithSection, new() { new ("General Information", "/course/general"),
                                 new ("Link and Image", "/course/link"),
                                 new ("Overview", "/course/overview"),
                                 new ("Filters", "/course/filters"),
                                 new ("Related Links", "/course/relatedlinks"),
                                 new ("Section List", "/course/sectionlist"),
                                 new ("Technical Information", "/course/technical") } },
            { SidebarEnum.Section, new() { new ("General Information", "/section/general"),
                                 new ("Location & Time", "/section/locationtime"),
                                 new ("Faculty", "/section/faculty"),
                                 new ("Technical Information", "/section/technical") } },
            { SidebarEnum.RequirementSets, new() { new ("Requirement Sets", "/requirementsets") } },
            { SidebarEnum.RequirementSet, new() { new ("General Information", "/requirementset/general"),
                                 new ("Courses", "/requirementset/courses"),
                                 new ("Technical Information", "/requirementset/technical") } },
            { SidebarEnum.Configuration, new() { new ("Sources", "/configuration/sources"),
                                 new ("Fields Used", "/configuration/fieldsused/programs"),
                                 new ("Manage Filters", "/configuration/filters"),
                                 new ("Security", "/configuration/security"),
                                 new ("Request Deletion", "/configuration/requestdeletion"),
                                 new ("Testing Access", "/configuration/testing"),
                                 new ("Save Information to JSON", "/configuration/savejson"),
                                 new ("Load JSON Information to the Server", "/configuration/loadjson") } },
            { SidebarEnum.ConfigurationNoSource, new() { new ("Sources", "/configuration/sources"),
                                 new ("Testing Access", "/configuration/testing") } },
            { SidebarEnum.FieldsUsed, new() { new ("Programs", "/configuration/fieldsused/programs"),
                                 new ("Credentials", "/configuration/fieldsused/credentials"),
                                 new ("Courses", "/configuration/fieldsused/courses"),
                                 new ("Sections", "/configuration/fieldsused/sections"),
                                 new ("Requirement Sets", "/configuration/fieldsused/requirementsets") } },
            { SidebarEnum.Audit, new() { new ("Access Logs", "/audit/changed") } }
        };

        public static List<PageLink>? GetBreadcrumbs(SidebarEnum s) => _breadcrumbs.TryGetValue(s, out var value) ? value : null;

        public static List<PageLink>? GetSidebar(SidebarEnum s) => _sidebars.TryGetValue(s, out var value) ? [.. value] : null;
    }
}